name: my workflow
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/docker-login@v1
        with:
          login-server: index.docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: |
          docker build . -t index.docker.io/${{ secrets.DOCKER_REPO }}:${{ github.sha }}
          docker push index.docker.io/${{ secrets.DOCKER_REPO }}:${{ github.sha }}
